services:
  db:
    image: mysql:8.0
    container_name: attendly-api-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendly_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: attendly-api-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:p6spy:mysql://db:3306/attendly_api?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.p6spy.engine.spy.P6SpyDriver
      SPRING_FLYWAY_REPAIR: "true"
      DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1368899732864503818/2kxY39C_ZOklifqUImZpYYp_5mSpWALlnHB2GUT7bAQjpaOjGM3MU7N1YfRUWlt9B0_Q
      TZ: Asia/Seoul
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-data: 