spring:
  application:
    name: attendly-api
  security:
    jwt:
      secret-key: W69y1eJ8PbhfCHWTrTQrNcSY5yYOVBvTmcSoKVGpMxj0rIrx
      expiration-time: 3600000  # 1시간
      refresh-expiration-time: 2592000000  # 30일
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha 