spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/attendly_api?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Discord 웹훅 설정
discord:
  webhook:
    url: https://discord.com/api/webhooks/1372565578954309642/G94sGsXYBLOJe08bI0esT9hafeMYCGjo-tRzk7rnEDMJqRAHc2CH1amZpi4k9awxy_Xm
    min-level: DEBUG

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.attendly: DEBUG
    p6spy: DEBUG 