spring:
  application:
    name: attendly-api
  security:
    jwt:
      secret-key: W69y1eJ8PbhfCHWTrTQrNcSY5yYOVBvTmcSoKVGpMxj0rIrx
      expiration-time: 3600000  # 1시간
      refresh-expiration-time: 2592000000  # 30일
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    vault:
      token: ${SPRING_CLOUD_VAULT_TOKEN:00000000-0000-0000-0000-000000000000}
      authentication: token
      scheme: ${SPRING_CLOUD_VAULT_SCHEME:http}
      host: ${SPRING_CLOUD_VAULT_HOST:localhost}
      port: ${SPRING_CLOUD_VAULT_PORT:8200}
      kv:
        enabled: true
        backend: secret
        default-context: attendly-api
  config:
    import: vault://

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
